version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_AR"
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: "skoll.ar"

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.enable: "true"
      traefik.docker.network: "inverseproxy_shared"
      traefik.tcp.services.mvptaller-15-0-prod-database.loadbalancer.server.port: 5432
      traefik.mvptaller-15-0-prod-database-0.port: 5432
      traefik.tcp.routers.mvptaller-15-0-prod-database-0.rule: Host(`skoll.ar`)
      traefik.tcp.routers.mvptaller-15-0-prod-database-0.service: mvptaller-15-0-prod-database

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  filestore:
  db:
